'use strict';
module.exports = {
    TODO_CREATE: 'TODO_CREATE',
    TODO_UPDATE_TEXT: 'TODO_UPDATE_TEXT',
    TODO_UNDO_COMPLETE: 'TODO_UNDO_COMPLETE',
    TODO_COMPLETE: 'TODO_COMPLETE',
    TODO_TOGGLE_COMPLETE_ALL: 'TODO_TOGGLE_COMPLETE_ALL',
    TODO_DESTROY: 'TODO_DESTROY',
    TODO_DESTROY_COMPLETED: 'TODO_DESTROY_COMPLETED'
};